// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nazqgumhstlrtebuzery.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5henFndW1oc3RscnRlYnV6ZXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyNDgzOTMsImV4cCI6MjA1MjgyNDM5M30.3hcow4-9KG9Vk11gevs422CI_tnnaWRNM_RGQ_-nGeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
